### ISSUE TITLE
Trying to run example on node 4.0.0

### ISSUE THREAD

**Issue by imaustink** [binocarlos/raspivid#8]
``` javascript
video.pipe(file);
      ^

TypeError: video.pipe is not a function
    at Object.<anonymous> (/home/pi/camera/app.js:7:7)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

```

Any ideas on how to fix this? I copy and pasted the example.

``` javascript
var raspivid = require('raspivid');
var fs = require('fs');

var file = fs.createWriteStream(__dirname + '/video.h264');
var video = raspivid();

video.pipe(file);
```

**Comment by imaustink** [comment]
It seems the NPM module is out of date. I tried the index file in the repo and it works fine.

**Comment by binocarlos** [comment]
@imaustink yikes you are totally right - I just pushed `1.0.0` to npm - thanks!
