### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cmegens** [binocarlos/raspivid#9]
So I installed node and npm.

Then I installed raspivid and fs through npm.

When I run the example I get the following error:

> child_process.js:921
>       throw new TypeError('Incorrect value for stdio stream: ' + stdio);
>             ^
> TypeError: Incorrect value for stdio stream: inherit
>     at child_process.js:921:13
>     at Array.reduce (native)
>     at ChildProcess.spawn (child_process.js:876:17)
>     at Object.exports.spawn (child_process.js:735:9)
>     at module.exports (/home/pi/CAM/node_modules/raspivid/index.js:22:29)
>     at Object.<anonymous> (/home/pi/CAM/video.js:3:13)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)

Any thoughts? Camera is working with both raspivid and motion.

**Comment by binocarlos** [comment]
@cmegens interesting - `inherit` seems to be a bad value for the stream

[this page](https://github.com/nodejs/node-v0.x-archive/issues/4030) mentions node `0.12` - which version are you running?
